export const travelPackages = [
    {
      id: 1,
      location: "Dutch and French Jewels",
      image: "https://images.unsplash.com/photo-1569949381669-ecf31ae8e613?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTZ8fGVpZmZlbCUyMHRvd2VyfGVufDB8fDB8fHwy",
      price: 79000,
      days: 6,
      rating: 4.7,
      destination:"western-europe",
      perks: ["4 Star Hotels", "Breakfast", "Sightseeing and Tours", "Transfers and Boat"],
      highlights: ["Amsterdam", "Paris"],
      itinerary: [
        { place: "Amsterdam", nights: 2 },
        { place: "Paris", nights: 3 },
      ],
    },
    {
      id: 2,
      location: "European Fusion",
      image: "https://images.unsplash.com/photo-1727478431219-a856111bca1b?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTR8fEV1cm9wZWFuJTIwRnVzaW9ufGVufDB8fDB8fHwy",
      price: 320000,
      days: 11,
      rating: 4.5,
      destination:"western-europe",
      perks: ["3 Star Hotels", "Breakfast", "Sightseeing and Tours", "Transfers and EURAIL"],
      highlights: ["Amsterdam", "Paris", "Zurich", "Innsbruck", "Venice"],
      itinerary: [
        { place: "Amsterdam", nights: 2 },
        { place: "Paris", nights: 2 },
        { place: "Zurich", nights: 3 },
        { place: "Innsbruck", nights: 2 },
        { place: "Venice", nights: 1 },
      ],
    },
    {
      id: 3,
      location: "Hallmarks of Europe",
      image: "https://images.unsplash.com/photo-1473951574080-01fe45ec8643?q=80&w=2104&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      price: 299000,
      days: 10,
      rating: 4.6,
      destination:"western-europe",
      perks: ["3 Star Hotels", "Breakfast", "Sightseeing and Tours", "Transfers and EURAIL"],
      highlights: ["London", "Paris", "Zurich", "Interlaken"],
      itinerary: [
        { place: "London", nights: 2 },
        { place: "Paris", nights: 3 },
        { place: "Zurich", nights: 2 },
        { place: "Interlaken", nights: 2 },
      ],
    },
    {
      id: 4,
      location: "Italian Fantasy",
      image: "https://images.unsplash.com/photo-1520175480921-4edfa2983e0f?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8SXRhbHl8ZW58MHx8MHx8fDI%3D",
      price: 220000,
      days: 9,
      rating: 4.8,
      destination:"western-europe",
      perks: ["3 Star Hotels", "Breakfast", "Sightseeing and Tours", "Transfers and EURAIL"],
      highlights: ["Rome", "Florence", "Venice", "Milan"],
      itinerary: [
        { place: "Rome", nights: 2 },
        { place: "Florence", nights: 2 },
        { place: "Venice", nights: 2 },
        { place: "Milan", nights: 2 },
      ],
    },
    {
      id: 5,
      location: "Small Europe",
      image: "https://images.unsplash.com/photo-1546610072-90a8cdd6aa4d?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      price: 188000,
      days: 8,
      rating: 4.4,
      destination:"western-europe",
      perks: ["3 Star Hotels", "Breakfast", "Sightseeing and Tours", "Transfers and EURAIL"],
      highlights: ["Amsterdam", "Brussels", "Luxembourg"],
      itinerary: [
        { place: "Amsterdam", nights: 2 },
        { place: "Brussels", nights: 3 },
        { place: "Luxembourg", nights: 2 },
      ],
    },
    {
      id: 6,
      location: "Spain and Portugal",
      image: "https://images.unsplash.com/photo-1509840841025-9088ba78a826?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8c3BhaW58ZW58MHx8MHx8fDI%3D",
      price: 110000,
      days: 8,
      rating: 4.3,
      destination:"western-europe",
      perks: ["3 Star Hotels", "Breakfast", "Sightseeing and Tours", "Transfers and EURAIL"],
      highlights: ["Madrid", "Lisbon", "Porto", "Santiago De Compostela"],
      itinerary: [
        { place: "Madrid", nights: 2 },
        { place: "Lisbon", nights: 2 },
        { place: "Porto", nights: 1 },
        { place: "Santiago De Compostela", nights: 1 },
        { place: "Madrid", nights: 1 },
      ],
    },
    {
      id: 7,
      location: "Spanish Paradise",
      image: "https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8cG9ydHVnYWx8ZW58MHx8MHx8fDI%3D",
      price: 114000,
      days: 8,
      rating: 4.7,
      destination:"western-europe",
      perks: ["4 Star Hotels", "Breakfast", "Sightseeing and Tours", "Transfers and EURAIL"],
      highlights: ["Madrid", "Granada", "Seville", "Barcelona"],
      itinerary: [
        { place: "Madrid", nights: 2 },
        { place: "Granada", nights: 1 },
        { place: "Seville", nights: 2 },
        { place: "Barcelona", nights: 2 },
      ],
    },
    {
      id: 8,
      location: "True Colors of Turkey",
      image: "https://images.unsplash.com/photo-1510253687831-0f982d7862fc?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8dHVya2V5fGVufDB8fDB8fHwy",
      price: 98000,
      days: 8,
      rating: 4.6,
      destination:"dubai",
      perks: ["4 Star Hotels", "Breakfast", "Sightseeing and Tours", "Transfers and EURAIL"],
      highlights: ["Istanbul", "Ankara", "Cappadocia", "Safranbolu"],
      itinerary: [
        { place: "Istanbul", nights: 2 },
        { place: "Ankara", nights: 1 },
        { place: "Cappadocia", nights: 2 },
        { place: "Safranbolu", nights: 1 },
        { place: "Istanbul", nights: 1 },
      ],
    },
    {
      id: 9,
      location: "Western Turkish Wonders",
      image: "https://images.unsplash.com/photo-1623621534850-d325a1980c7e?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTZ8fHR1cmtleXxlbnwwfHwwfHx8Mg%3D%3D",
      price: 75000,
      days: 6,
      rating: 4.5,
      destination:"dubai",
      perks: ["4 Star Hotels", "Breakfast", "Sightseeing and Tours", "Transfers and EURAIL"],
      highlights: ["Istanbul", "Kusadasi"],
      itinerary: [
        { place: "Istanbul", nights: 3 },
        { place: "Kusadasi", nights: 1 },
        { place: "Istanbul", nights: 1 },
      ],
    },
    {
      id: 10,
      location: "Wonders of Europe",
      image: "https://images.unsplash.com/photo-1555992828-35627f3b373f?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OXx8Q29sb3NzZXVtfGVufDB8fDB8fHwy",
      price: 158000,
      days: 10,
      rating: 4.8,
      destination:"western-europe",
      perks: ["4 Star Hotels", "Breakfast", "Sightseeing and Tours", "Transfers and EURAIL"],
      highlights: ["Rome", "Florence", "Venice", "Zurich", "Paris"],
      itinerary: [
        { place: "Rome", nights: 2 },
        { place: "Florence", nights: 1 },
        { place: "Venice", nights: 1 },
        { place: "Zurich", nights: 2 },
        { place: "Paris", nights: 3 },
      ],
    },
    {
      id: 11,
      location: "Beautiful Austria",
      image: "https://images.unsplash.com/photo-1597086831879-756db15e81d3?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8QXVzdHJpYXxlbnwwfHwwfHx8Mg%3D%3D",
      price: 178000,
      days: 7,
      rating: 4.4,
      destination:"central-europe",
      perks: ["3 Star Hotels", "Breakfast", "Sightseeing and Tours", "Transfers and EURAIL"],
      highlights: ["Vienna", "Salzburg", "Innsbruck"],
      itinerary: [
        { place: "Vienna", nights: 2 },
        { place: "Salzburg", nights: 2 },
        { place: "Innsbruck", nights: 2 },
      ],
    },
    {
      id: 12,
      location: "Cultural Europe",
      image: "https://images.unsplash.com/photo-1690301489328-94dfb7e7b37b?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTR8fEN1bHR1cmFsJTIwRXVyb3BlfGVufDB8fDB8fHwy",
      price: 168000,
      days: 12,
      rating: 4.7,
      destination:"central-europe",
      perks: ["4 Star Hotels", "Breakfast", "Sightseeing and Tours", "Transfers and Boat"],
      highlights: ["Rome", "Florence", "Venice", "Kitzbuhel", "Vienna", "Budapest", "Prague", "Frankfurt"],
      itinerary: [
        { place: "Rome", nights: 2 },
        { place: "Florence", nights: 1 },
        { place: "Venice", nights: 1 },
        { place: "Kitzbuhel", nights: 1 },
        { place: "Vienna", nights: 2 },
        { place: "Budapest", nights: 1 },
        { place: "Prague", nights: 2 },
        { place: "Frankfurt", nights: 1 },
      ],
    },
    {
      id: 13,
      location: "East European Paradise",
      image: "https://images.unsplash.com/photo-1568209166532-cfab434e43a3?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8ZWFzdGVybiUyMGV1cm9wZXxlbnwwfHwwfHx8Mg%3D%3D",
      price: 238000,
      days: 9,
      rating: 4.6,
      destination:"eastern-europe",
      perks: ["3 Star Hotels", "Breakfast", "Sightseeing and Tours", "Transfers and EURAIL"],
      highlights: ["Prague", "Vienna", "Budapest", "Ljubljana", "Salzburg"],
      itinerary: [
        { place: "Prague", nights: 2 },
        { place: "Vienna", nights: 1 },
        { place: "Budapest", nights: 2 },
        { place: "Ljubljana", nights: 2 },
        { place: "Salzburg", nights: 1 },
      ],
    },
    {
      id: 14,
      location: "Eastern European Capitals",
      image: "https://images.unsplash.com/photo-1491900177661-4e1cd2d7cce2?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8RWFzdGVybiUyMEV1cm9wZWFuJTIwQ2FwaXRhbHN8ZW58MHx8MHx8fDI%3D",
      price: 69000,
      days: 6,
      rating: 4.3,
      destination:"eastern-europe",
      perks: ["4 Star Hotels", "Breakfast", "Sightseeing and Tours", "Transfers and EURAIL"],
      highlights: ["Vienna", "Budapest", "Prague"],
      itinerary: [
        { place: "Vienna", nights: 2 },
        { place: "Budapest", nights: 1 },
        { place: "Prague", nights: 2 },
      ],
    },
  ];